# Generated by cpp11: do not edit by hand

C_murphydiag_expect <- function(x, y, level) {
  .Call(`_triptych_C_murphydiag_expect`, x, y, level)
}

C_murphydiag_median <- function(x, y) {
  .Call(`_triptych_C_murphydiag_median`, x, y)
}

C_murphydiag_prob <- function(x, y) {
  .Call(`_triptych_C_murphydiag_prob`, x, y)
}

C_murphydiag_prob_ref <- function(x, y, ref) {
  .Call(`_triptych_C_murphydiag_prob_ref`, x, y, ref)
}
